// <auto-generated />
using System;
using Link.Cloud.SagaStateMachine.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Link.Cloud.SagaStateMachine.Migrations
{
    [DbContext(typeof(EventStateDbContext))]
    partial class EventStateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Link.Cloud.SagaStateMachine.Models.EventStateInstance", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CorrelationId");

                    b.ToTable("EventStateInstance");
                });

            modelBuilder.Entity("Link.Cloud.SagaStateMachine.Models.UserRoleName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EventStateInstanceCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventStateInstanceCorrelationId");

                    b.ToTable("UserRoleName");
                });

            modelBuilder.Entity("Link.Cloud.SagaStateMachine.Models.UserRoleName", b =>
                {
                    b.HasOne("Link.Cloud.SagaStateMachine.Models.EventStateInstance", "EventStateInstance")
                        .WithMany("UserRoleNames")
                        .HasForeignKey("EventStateInstanceCorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventStateInstance");
                });

            modelBuilder.Entity("Link.Cloud.SagaStateMachine.Models.EventStateInstance", b =>
                {
                    b.Navigation("UserRoleNames");
                });
#pragma warning restore 612, 618
        }
    }
}
